Populate empty variable before sending to Slack
If $COULD_NOT_MIRROR exists, but is empty, the slack message will fail.

```
Error: failed to match all allowed schemas [json-pointer:/blocks/2/text]
Error: must be more than 0 characters [json-pointer:/blocks/2/text/text]
```

So we should ensure that it's not empty.